name: meshpix
description: MeshCore companion for tiny LoRa image transfer.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  app_links: ^7.0.0
  archive: ^4.0.7
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^2.3.12
  image_picker: ^1.1.2
  permission_handler: ^13.0.1
  provider: ^6.1.5
  image: ^4.9.2
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
